<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Impact</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="_Impact_files/libs/clipboard/clipboard.min.js"></script>
<script src="_Impact_files/libs/quarto-html/quarto.js"></script>
<script src="_Impact_files/libs/quarto-html/popper.min.js"></script>
<script src="_Impact_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="_Impact_files/libs/quarto-html/anchor.min.js"></script>
<link href="_Impact_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="_Impact_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="_Impact_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="_Impact_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="_Impact_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

<script src="_Impact_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="_Impact_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Impact</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>The following questions were asked in regards to the impact of Basic Needs programs and services on students lives. Students were asked to evaluate how they feel these programs have benefited them both academically and non-academically, as well as barriers/reasons in regards to why they are not using certain programs. This includes programs such as CalFresh, Food Pantries, Medi-Cal (also known as Medi-Cade in the United States), and Emergency Housing Services.</p>
<p><br></p>
<section id="calfresh-ebt" class="level2">
<h2 class="anchored" data-anchor-id="calfresh-ebt">CalFresh EBT</h2>
<p><em>Note: for the first graph on EBT application we have (n=652, 31% of 2110 reporting) And for the second graph on how many people are fed we have (n=620, 29% of 2110 reporting)</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
<p>Looking at the above graphs, the majority of people apply for CalFresh EBT as an individual (355 people) while only 297 people applied with other people in their household. Similarly, the majority of people claimed only 1 person is fed through the EBT card (230 people). 138 people claim to feed 2 people through the EBT card, and only a small amount of people claim to feed 5 or more people through the EBT card.</p>
<p><br></p>
<section id="monthly-calfresh-money" class="level3">
<h3 class="anchored" data-anchor-id="monthly-calfresh-money">Monthly CalFresh Money</h3>
<p><strong>How much money do you receive from CalFresh each month? (n=634, 30% of 2110 reporting)</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The average amount of money received per household using CalFresh (denoted by the dotted line) is $305.91, while the median is $250. The values range from $0 to $1500. The majority of households who do receive these benefits seems to be getting around $250 or less per month.</p>
</section>
<section id="household-size-breakdown" class="level3">
<h3 class="anchored" data-anchor-id="household-size-breakdown">Household Size Breakdown</h3>
<p>Below is a breakdown of the average monthly allowance received from CalFresh based on household size.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Household Size</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Household Average</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Per Person Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">$196.58</td>
<td style="text-align: left;">$196.58</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">$309.51</td>
<td style="text-align: left;">$154.76</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">$387.99</td>
<td style="text-align: left;">$129.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">$450.56</td>
<td style="text-align: left;">$112.64</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">$453.57</td>
<td style="text-align: left;">$ 90.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">$536.85</td>
<td style="text-align: left;">$ 89.48</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: left;">$521.00</td>
<td style="text-align: left;">$ 74.43</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">$402.14</td>
<td style="text-align: left;">$ 50.27</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;"></td>
<td style="text-align: left; font-weight: bold;">Total Average</td>
<td style="text-align: left; font-weight: bold;">$112.28</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Looking at the above table, the general pattern seems to be that as household size increases so does the monthly average assistance from CalFresh. The household average was divided by the household size to find the “per person average” for CalFresh assistance. From taking the average of these values, we can see that a person on CalFresh receives an average monthly assistance of $112.28.</p>
</section>
<section id="is-this-enough" class="level3">
<h3 class="anchored" data-anchor-id="is-this-enough">Is This Enough?</h3>
<p><em>Note: for the first graph on if the allowance is enough we have (n=623, 30% of 2110 reporting) And for the second graph on when people run out we have (n=586, 28% of 2110 reporting)</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>Of the people who do receive money from CalFresh, 224 of them agree that it is enough money to provide healthy food for a month and 288 of them feel that it is not enough. People typically run out of CalFresh money in the first week (127 people), the second week (156 people) or the third week (160 people). A smaller minority run out within the fourth week or do not use up all their monthly balance.</p>
<p><br></p>
</section>
</section>
<section id="calfresh-benefits" class="level2">
<h2 class="anchored" data-anchor-id="calfresh-benefits">CalFresh Benefits</h2>
<p><strong>While you received CalFresh benefits:</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="calfresh-barriers" class="level2">
<h2 class="anchored" data-anchor-id="calfresh-barriers">CalFresh Barriers</h2>
<p><strong>What are the reasons you do not have CalFresh or have never used CalFresh? (Select all that apply).</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Measure</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I do not think I am eligible. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">419 (37.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I feel other students need CalFresh more than I do. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">210 (18.6%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No time to complete the application/ application is too long. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">191 (16.9%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't need CalFresh. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">180 (15.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The application is too difficult. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">147 (13.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">No time to call or go to the local social services office for my CalFresh interview. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">144 (12.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other (Please specify). (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">139 (12.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">It's too difficult to get my verification documents. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">119 (10.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I feel uncomfortable receiving help with basic needs, like food. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">76 (6.7%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">The staff in my local county social services office were not helpful or supportive during my application process. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">75 (6.6%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I have heard that it's not worth my time because I won't be eligible or I won't receive much money. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">73 (6.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">My family or household does not want to apply for CalFresh. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">70 (6.2%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I am embarrassed or ashamed to apply for CalFresh. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">62 (5.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">The CalFresh outreach team on campus was not helpful or supportive during my application process. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">44 (3.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't wan't my friends to find out I'm receiving food assistance. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">39 (3.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I would think less of myself if I applied for CalFresh. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">33 (2.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">No transportation to CalFresh office or social services office. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">28 (2.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">My friends and peers would think less of me if I apply for CalFresh. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">21 (1.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don't believe in social services like CalFresh, WIC, or Welfare. (n = 1129)</td>
<td style="text-align: left; width: 3.5cm;">2 (0.2%)</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="food-pantry-use" class="level2">
<h2 class="anchored" data-anchor-id="food-pantry-use">Food Pantry Use</h2>
<p><strong>How often do you normally use the food pantry or if you are not currently using it, how often did you use it? (n=500, 24% of 2110 reporting)</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>When people use the food pantry, the majority do not use it every week (235 people). 180 people claim to use it about once a week, 27 people use it more than once a week, and 58 people claim other uses.</p>
</section>
<section id="impact-of-pantry" class="level1">
<h1>Impact of Pantry</h1>
<p><strong>For the following questions, please choose how much you agree or disagree with the impact campus food pantries has or had on your life. While I utilized campus food pantry/pantries:</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
</div>
<section id="reasons-not-using-food-pantries" class="level3">
<h3 class="anchored" data-anchor-id="reasons-not-using-food-pantries">Reasons Not Using Food Pantries</h3>
<p><strong>What are the reasons for you to not go to campus food pantries? (Select all that apply).</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Measure</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I feel other students need the food more than I do. (n = 1267)</td>
<td style="text-align: left;">386 (30.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't need to use campus food pantries. (n = 1267)</td>
<td style="text-align: left;">332 (26.2%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I am not aware of any campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">262 (20.7%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Inconvenient to access due to lack of transportation or out-of-the way location. (n = 1267)</td>
<td style="text-align: left;">213 (16.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Inconvenient times of operation/limited pantry hours. (n = 1267)</td>
<td style="text-align: left;">210 (16.6%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I am embarrassed or scared to go to the campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">208 (16.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I feel uncomfortable about receiving help with basic needs, like food. (n = 1267)</td>
<td style="text-align: left;">155 (12.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other (n = 1267)</td>
<td style="text-align: left;">74 (5.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I would think less of myself If I went to campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">57 (4.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't want my friends to find out I go to campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">43 (3.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">There are no food pantries close to campus or my residence. (n = 1267)</td>
<td style="text-align: left;">39 (3.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">My friends and peers would think less of me if I went to campus table(food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">30 (2.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">My family doesn't want me to go to campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">27 (2.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I do not believe in using campus food pantries or local food banks. (n = 1267)</td>
<td style="text-align: left;">4 (0.3%)</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="medi-cal" class="level2">
<h2 class="anchored" data-anchor-id="medi-cal">Medi-Cal</h2>
<p><strong>Knowing that you have Medi-Cal:</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
</div>
<section id="reasons-not-using-medi-cal" class="level3">
<h3 class="anchored" data-anchor-id="reasons-not-using-medi-cal">Reasons Not Using Medi-Cal</h3>
<p><strong>What are the reasons you do not have Medi-Cal or have never used Medi-Cal? (Select all that apply).</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Measure</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I do not know what MediCal is or I think I already have health insurance. (n = 526)</td>
<td style="text-align: left;">145 (27.6%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don’t need MediCal. (n = 526)</td>
<td style="text-align: left;">139 (26.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I do not think I am eligible for MediCal. (n = 526)</td>
<td style="text-align: left;">117 (22.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Other (n = 526)</td>
<td style="text-align: left;">95 (18.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The MediCal application is too difficult to complete. (n = 526)</td>
<td style="text-align: left;">39 (7.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">No time to complete the MediCal application/MediCal application is too long. (n = 526)</td>
<td style="text-align: left;">33 (6.3%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I only need medical services at the student health center associated with my campus. (n = 526)</td>
<td style="text-align: left;">21 (4.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I feel uncomfortable about receiving help with basic needs, like food. (n = 526)</td>
<td style="text-align: left;">8 (1.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I have heard from other students that it is not worth my time because I wont be eligible. (n = 526)</td>
<td style="text-align: left;">7 (1.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">My family or household does not want me to apply for MediCal. (n = 526)</td>
<td style="text-align: left;">5 (1.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I am embarrassed or ashamed to apply for MediCal. (n = 526)</td>
<td style="text-align: left;">5 (1.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I would think less of myself If I went to campus food pantries or local food banks. (n = 526)</td>
<td style="text-align: left;">2 (0.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I don’t believe in social services like MediCal, CalFresh, WIC, or Welfare/Cash Aid. (n = 526)</td>
<td style="text-align: left;">1 (0.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't want my friends to find out I go to campus food pantries or local food banks. (n = 526)</td>
<td style="text-align: left;">0 (0.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">My friends and peers would think less of me if I went to campus table(food pantries or local food banks. (n = 526)</td>
<td style="text-align: left;">0 (0.0%)</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="emergency-housing-services-ehs" class="level2">
<h2 class="anchored" data-anchor-id="emergency-housing-services-ehs">Emergency Housing Services (EHS)</h2>
<p><strong>While you received Emergency Housing Services:</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="_Impact_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
</div>
<section id="reasons-not-using-ehs" class="level3">
<h3 class="anchored" data-anchor-id="reasons-not-using-ehs">Reasons Not Using EHS</h3>
<p><strong>What are the reasons you do not have Emergency Housing Services or have never used Emergency Housing Services?</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Measure</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I don’t need Emergency Housing Services (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">1062 (62.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I was not aware that my campus had Emergency Housing Services like grants and housing placements in an emergency. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">628 (37.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">60 (3.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">No time to complete the Emergency Housing application or contact the Emergency Housing Staff. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">59 (3.5%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I feel uncomfortable about receiving help with basic needs, like housing. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">54 (3.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I am embarrassed or ashamed to apply for Emergency Housing Services. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">46 (2.7%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">The emergency housing grant/money is not enough to support what I need, so not worth my time to apply for it. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">40 (2.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">The Emergency Housing Services application is too difficult to complete. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">33 (1.9%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">I would think less of myself if I applied for Emergency Housing Services. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">26 (1.5%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I don't want my friends to find out that I applied for emergency housing services. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">17 (1.0%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">My friends and peers would think less of me if I applied for emergency housing services. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">14 (0.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I do not believe in social services like Emergency Housing Services, MediCal, CalFresh, or Welfare/Cash Aid. (n = 1698)</td>
<td style="text-align: left; width: 3.5cm;">1 (0.1%)</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>