<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>BNS Statewide - Demographics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">BNS Statewide</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html" rel="" target="">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./Demographics.html" rel="" target="" aria-current="page">
 <span class="menu-text">Demographics</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Workload.html" rel="" target="">
 <span class="menu-text">Workload</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Housing.html" rel="" target="">
 <span class="menu-text">Housing</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./CalFresh.html" rel="" target="">
 <span class="menu-text">CalFresh</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Food_Security.html" rel="" target="">
 <span class="menu-text">Food Security</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Eating_Habits.html" rel="" target="">
 <span class="menu-text">Eating Habits</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Physical_Activity.html" rel="" target="">
 <span class="menu-text">Physical Activity</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Mental_Health.html" rel="" target="">
 <span class="menu-text">Mental Health</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools ms-auto">
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#personal-demographics" id="toc-personal-demographics" class="nav-link active" data-scroll-target="#personal-demographics">Personal Demographics</a>
  <ul class="collapse">
  <li><a href="#age" id="toc-age" class="nav-link" data-scroll-target="#age">Age</a></li>
  <li><a href="#gender-identity" id="toc-gender-identity" class="nav-link" data-scroll-target="#gender-identity">Gender Identity</a></li>
  <li><a href="#ethnicity-i.e.-identifying-with-hispanic-origin" id="toc-ethnicity-i.e.-identifying-with-hispanic-origin" class="nav-link" data-scroll-target="#ethnicity-i.e.-identifying-with-hispanic-origin">Ethnicity (i.e.&nbsp;Identifying with Hispanic Origin)</a></li>
  <li><a href="#race" id="toc-race" class="nav-link" data-scroll-target="#race">Race</a></li>
  <li><a href="#dependents" id="toc-dependents" class="nav-link" data-scroll-target="#dependents">Dependents</a></li>
  <li><a href="#parents-education" id="toc-parents-education" class="nav-link" data-scroll-target="#parents-education">Parents Education</a></li>
  <li><a href="#first-generation" id="toc-first-generation" class="nav-link" data-scroll-target="#first-generation">First Generation</a></li>
  </ul></li>
  <li><a href="#academic-characteristics" id="toc-academic-characteristics" class="nav-link" data-scroll-target="#academic-characteristics">Academic Characteristics</a>
  <ul class="collapse">
  <li><a href="#school" id="toc-school" class="nav-link" data-scroll-target="#school">School</a></li>
  <li><a href="#class-standing" id="toc-class-standing" class="nav-link" data-scroll-target="#class-standing">Class Standing</a></li>
  <li><a href="#major" id="toc-major" class="nav-link" data-scroll-target="#major">Major</a></li>
  <li><a href="#overall-gpa" id="toc-overall-gpa" class="nav-link" data-scroll-target="#overall-gpa">Overall GPA</a></li>
  <li><a href="#currently-enrolled-units" id="toc-currently-enrolled-units" class="nav-link" data-scroll-target="#currently-enrolled-units">Currently Enrolled Units</a></li>
  </ul></li>
  <li><a href="#student-identifiers" id="toc-student-identifiers" class="nav-link" data-scroll-target="#student-identifiers">Student Identifiers</a>
  <ul class="collapse">
  <li><a href="#i-identify-as" id="toc-i-identify-as" class="nav-link" data-scroll-target="#i-identify-as">I identify as…</a></li>
  <li><a href="#disability-support-services" id="toc-disability-support-services" class="nav-link" data-scroll-target="#disability-support-services">Disability Support Services</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Demographics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="personal-demographics" class="level1">
<h1>Personal Demographics</h1>
<p>Students’ personal demographics (e.g.&nbsp;age, ethnicity, number of dependents, etc.) were obtained and visualized in this section. Specific survey questions and summaries are found below each figure.</p>
<section id="age" class="level2">
<h2 class="anchored" data-anchor-id="age">Age</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-age" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-age-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;1.1: Reported age (years) by college students (n=2110, 100% of 2110 reporting)</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey question: </strong> <em>What is your date of birth?</em></p>
<p><strong>Summary: </strong> Student age was determined by the difference between birth date and the time in which the survey was completed. Students’ (n=2110, 100% of 2110 reporting) average age is 24.6 years with a range of 18 to 72 and the majority falling between 20-30 years old.</p>
<p><br></p>
</section>
<section id="gender-identity" class="level2">
<h2 class="anchored" data-anchor-id="gender-identity">Gender Identity</h2>
<div class="row">

<div class="col-md-7">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-gender" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-gender-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1.2: Reported gender identity by college students (n=2094, 99% of 2110 reporting)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<p><strong>Survey question: </strong> <em>What is your gender identity?</em></p>
<p><strong>Summary: </strong> 1642 (78.4%) of the students identify as a woman, 407 (19.4%) identify as a man, and 42 (2.0%) identify as gender non-binary and queer/non-conforming, respectively. Remaining students who preferred not to answer.</p>
<p><br></p>
</div></section>
<section id="ethnicity-i.e.-identifying-with-hispanic-origin" class="level2">
<h2 class="anchored" data-anchor-id="ethnicity-i.e.-identifying-with-hispanic-origin">Ethnicity (i.e.&nbsp;Identifying with Hispanic Origin)</h2>
<div class="row">
<div class="col-md-6">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-hispanic" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-hispanic-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;1.3: Reported ethnic/Hispanic identity by college students (n=2070, 98% of 2110 reporting)</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="col-md-5">
<p><strong>Survey Question: </strong> <em>Do you identify as Hispanic or Latino or Spanish Origin?</em></p>
<p>Possible answers were those pulled from the U.S. Census questionnaire and Hispanic Origin included: <em>Mexican, Mexican American, Chicano, Puerto Rican, or another Hispanic/Latino/Spanish origin.</em></p>
<p><strong>Summary: </strong> 1436 (69.4%) of the students self-identify as having Hispanic Origins and 634 (30.6%) of the students self-identify as Non-Hispanic.</p>
</div>
</div>
<p><br></p>
</section>
<section id="race" class="level2">
<h2 class="anchored" data-anchor-id="race">Race</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="tbl-race" class="anchored">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<caption>Table&nbsp;1.1: Reported race by college students (n=2110, 100% of 2110 reporting)</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Identified Race</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">White</td>
<td style="text-align: left;">859 (38.2%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Prefer not to answer race</td>
<td style="text-align: left;">755 (33.6%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Asian</td>
<td style="text-align: left;">321 (14.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Black or African American</td>
<td style="text-align: left;">167 (7.4%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">American Indian and Alaska Native</td>
<td style="text-align: left;">106 (4.7%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">Native Hawaiian and Other Pacific Islander</td>
<td style="text-align: left;">40 (1.8%)</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><strong>Survey Question: </strong> <em>What race do you identify as? (Select all that apply)</em></p>
<p>Possible answers were those pulled from the U.S. Census questionnaire and included: White, Black or African American, American Indian or Alaska Native, Chinese, Filipino, Asian Indian, Vietnamese, Korean, Japanese, Other Asian, Native Hawaiian, Samoan, Chamorro, Other Pacific Islander. Although “Prefer not to answer” was an option, “Do not know” was not an option. These 14 options were collapsed into the 5 broad U.S. Census groups due to sample size variations.</p>
<p><strong>Summary: </strong> 859 (40.7%) of the students self-identify as White, 321 (15.2%) as Asian, 167 (7.9%) as Black or African American, 106 (5.0%) as American Indian and Alaskan Native and 40 (1.9%) as Native Hawaiian or Other Pacific Islander. 755 (35.8%) %) prefer not to answer race identity.</p>
<p><br></p>
</section>
<section id="dependents" class="level2">
<h2 class="anchored" data-anchor-id="dependents">Dependents</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-q11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-q11-1.png" class="img-fluid figure-img" width="576"></p>
<figcaption class="figure-caption">Figure&nbsp;1.4: Reported dependents by college students (n=2078, 98% of 2110 reporting). Students reporting no dependents or dependents without more than 50% financial support (n=1478) were not included.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question: </strong> <em>If you have dependents, then how many of them receive more than 50% of their financial support from you?</em></p>
<p><strong>Summary: </strong> 493 of the students reporting have dependents who receive more than 50% of their financial support. Of those with dependents, 213 (43.2%) have one dependent, 151 (30.6%) have two and the 128 (26.0%) students have more than 3 dependents.</p>
<p><br></p>
</section>
<section id="parents-education" class="level2">
<h2 class="anchored" data-anchor-id="parents-education">Parents Education</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-q13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-q13-1.png" class="img-fluid figure-img" width="720"></p>
<figcaption class="figure-caption">Figure&nbsp;1.5: Parent/guardian education level reported by college students (n=2083, 99% of 2110 reporting). These data will determine a student’s First Generation status. First Generation status is defined by neither parent having completed a Bachelor’s degree or higher. Data in yellow categories (minus Other/Unknown) are added to determine total number of First generation status in <a href="#fig-firstgen">Figure&nbsp;1.6</a> (below).</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question: </strong> <em>What is the highest level of education completed by your parents/guardians (for example, if your mother and father both raised you, and your mother has the highest level of education, then indicate her highest level of education)?</em></p>
<p><strong>Summary: </strong>1892 (93.8%) of all students report first generation status based on their parent/guardian education level. This outcome is not surprising because the students were either enrolled in EOP or EOPS and both programs recruit students with first generation status. 1697 (81.5%) of students reported that their parents/guardians had less than an Associate’s degree, and 584 (28.0%) of those students reported their parents/guardians did not have a high school diploma or GED.</p>
<p><br></p>
</section>
<section id="first-generation" class="level2">
<h2 class="anchored" data-anchor-id="first-generation">First Generation</h2>
<div class="row">
<div class="col-md-6">
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-firstgen" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-firstgen-1.png" class="img-fluid figure-img" width="384"></p>
<figcaption class="figure-caption">Figure&nbsp;1.6: Reported First Generation status by college students (n=2017, 96% of 2110 reporting). First Generation status is defined by the University of California neither parent having completed a Bachelor’s degree or higher. Data from <a href="#fig-q13">Figure&nbsp;1.5</a> (above) in yellow categories (minus Other/Unknown) are added to determine total number of students with First generation status.</figcaption>
</figure>
</div>
</div>
</div>
</div>
<div class="col-md-5">
<p><strong>Calculated from previous Survey Question: </strong> <em>What is the highest level of education completed by your parents/guardians (for example, if your mother and father both raised you, and your mother has the highest level of education, then indicate her highest level of education)?</em></p>
</div>
</div>
<p><strong>Summary: </strong> 1892 (93.8%) of all students report First Generation status. As stated above, this outcome is not surprising because the students were either enrolled in EOP or EOPS and both programs recruit students with first generation status.</p>
<p><br></p>
</section>
</section>
<section id="academic-characteristics" class="level1">
<h1>Academic Characteristics</h1>
<p>The following set of questions were asked in regards to the students’ academic status. This includes information such as what college they are currently enrolled in, their class standing, major, GPA, and enrolled units. They were also asked questions about programs they participate in as well as what type of student they are (transfer, international, etc.) to help identify variables that may influence or correlate with other responses.</p>
<section id="school" class="level2">
<h2 class="anchored" data-anchor-id="school">School</h2>
<div class="row">

<div class="col-md-7">


<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-school" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Demographics_files/figure-html/fig-school-1.png" class="img-fluid figure-img" width="768"></p>
<figcaption class="figure-caption">Figure&nbsp;2.1: California College Campuses (n=12) associated with college students participating (n=2110) in this study. Individual campus is identified based on the college student’s official campus email account. University of California (UC) campus (n=1) is designated in blue, California State University (CSU) campuses (n=6) are designated in red and California Community College (CCC) campuses (n=5) are designated in gold.</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Survey Question: </strong> N/A</p>
<p><strong>Summary: </strong>1238 (58.7%), 690 (32.7%) and 182 (8.6%) of college students who completed the survey (n=2110) are enrolled in CSU, CCC and UC, respectively. All college students were either in the Educational Opportunity Program (EOP) at the UC or CSU systems or in the Extended Opportunity Programs and Services (EOPS). As of Fall 2020, there were 31,553 students in the CSU EOP.</p>
<p><br></p>
</div></div></section>
<section id="class-standing" class="level2">
<h2 class="anchored" data-anchor-id="class-standing">Class Standing</h2>
<p><strong>Estimate your class standing by units completed (do not include units from this semester/quarter): (n=2065, 98% of 2110 reporting)</strong></p>
<div class="row">

<div class="col-md-7">


<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Demographics_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>The statewide survey captures students of all class standing. Of the 2065 students, there were 565 freshmen, 433 sophomores, 579 juniors, and 444 seniors.</p>
<p><br></p>
</div></div></section>
<section id="major" class="level2">
<h2 class="anchored" data-anchor-id="major">Major</h2>
<p><strong>Which of the following categories best describes your major? (n=2089, 99% of 2110 reporting)</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Demographics_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
</div>
<p><em>NOTE: Science, Technology, Engineering and Math (STEM) was shortened for the figure above, but also includes the following majors: Medicine, Computer Science, Agriculture, Accounting, Statistics, Nursing, and Nutrition.</em></p>
<p>The majority of students in the data are majoring in a Public Health, Social Services, Social Science, and Education program (680 students). 624 of the students are Science, Technology, Engineering and Math (STEM) majors.</p>
<p><br></p>
</section>
<section id="overall-gpa" class="level2">
<h2 class="anchored" data-anchor-id="overall-gpa">Overall GPA</h2>
<p><strong>What is your approximate overall grade point average (GPA)? Remember that your GPA is on a scale from 0 to 4.0 (n=2063, 98% of 2110 reporting)</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Demographics_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="528"></p>
</figure>
</div>
</div>
</div>
<p>The average overall GPA for students is 3.31, while the median is 3.4. The majority (65.5%) of students have a GPA greater than 3.0.</p>
<p><br></p>
</section>
<section id="currently-enrolled-units" class="level2">
<h2 class="anchored" data-anchor-id="currently-enrolled-units">Currently Enrolled Units</h2>
<p><strong>How many units are you currently taking? (n=2090, 99% of 2110 reporting)</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Demographics_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The average number of units a student is enrolled in is 12.86 units, while the median is 13 units. The majority of students are considered full-time (12 or more units), with 12 units being the highest occurring and 15 units being the second highest occurring.</p>
<p><br></p>
</section>
</section>
<section id="student-identifiers" class="level1">
<h1>Student Identifiers</h1>
<p>The following tables contain separate questions that were asked as a series of Yes/No responses to help further understand students. They were grouped together in this page by the start of the question.</p>
<section id="i-identify-as" class="level2">
<h2 class="anchored" data-anchor-id="i-identify-as">I identify as…</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">A Transfer Student. (n = 2008)</td>
<td style="text-align: left; width: 3.5cm;">742 (37.0%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">An ESL (English as a Second Language) student. (n = 2020)</td>
<td style="text-align: left; width: 3.5cm;">581 (28.8%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">LGBTQA+. (n = 1997)</td>
<td style="text-align: left; width: 3.5cm;">295 (14.8%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A student with a disability. (n = 2013)</td>
<td style="text-align: left; width: 3.5cm;">248 (12.3%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A DREAM (i.e. undocumented) student. (n = 2081)</td>
<td style="text-align: left; width: 3.5cm;">148 (7.1%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A former foster youth/child. (n = 2084)</td>
<td style="text-align: left; width: 3.5cm;">127 (6.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A non-California resident (not International). (n = 2059)</td>
<td style="text-align: left; width: 3.5cm;">76 (3.7%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">A DACA (i.e. Deferred Action for Childhood Arrivals) student. (n = 2073)</td>
<td style="text-align: left; width: 3.5cm;">65 (3.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A student athlete. (n = 2073)</td>
<td style="text-align: left; width: 3.5cm;">50 (2.4%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">An International student. (n = 2079)</td>
<td style="text-align: left; width: 3.5cm;">22 (1.1%)</td>
</tr>
<tr class="odd">
<td style="text-align: left;">A Veteran of military service. (n = 2100)</td>
<td style="text-align: left; width: 3.5cm;">14 (0.7%)</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><br></p>
</section>
<section id="disability-support-services" class="level2">
<h2 class="anchored" data-anchor-id="disability-support-services">Disability Support Services</h2>
<p><em>Note: This name varies by campus and may not always be called the Disability Support Service Center.</em></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<table class="table table-striped table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Yes (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">I identify as a student with a disability (n = 2013)</td>
<td style="text-align: left; width: 3.5cm;">248 (12.3%)</td>
</tr>
<tr class="even">
<td style="text-align: left;">I receive services through my campus for a disability (n = 2065)</td>
<td style="text-align: left; width: 3.5cm;">195 (9.4%)</td>
</tr>
</tbody>
</table>


</div>
</div>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>